import os
import uuid
import aiohttp
import base64
from typing import Optional
from aiohttp import ClientTimeout
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Configuration
USE_LOCAL_IMAGE = os.getenv("USE_LOCAL_IMAGE", "false").lower() == "true"
DRAWTHINGS_URL = os.getenv("DRAWTHINGS_URL", "http://127.0.0.1:7860/sdapi/v1/txt2img")

# HuggingFace configuration
HF_API_KEY = os.getenv("HF_TOKEN")  # Keep the same env var name
HF_API_URL = os.getenv(
    "HF_API_URL", 
    "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-3-medium-diffusers"
)

# Backend URL for image serving - configurable for different environments
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000")

# Get the correct path to static directory
backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
project_root = os.path.dirname(backend_dir)
CACHE_DIR = os.path.join(project_root, "static", "images")

# Determine which mode to use
if USE_LOCAL_IMAGE:
    MOCK = False  # Use local model
    logger.info(f"Using local DrawThings at: {DRAWTHINGS_URL}")
elif HF_API_KEY:
    MOCK = False
    logger.info("Using HuggingFace API")
else:
    MOCK = True
    logger.info("Using mock responses")

class HFException(Exception):
    """Base exception for HuggingFace API related errors."""
    pass


async def generate_image_drawthings(
    prompt: str, 
    width: int = 512, 
    height: int = 512
) -> dict:
    """
    Generate an image using local DrawThings API.
    
    :param prompt: The prompt to generate the image
    :param width: Image width
    :param height: Image height
    :return: Dictionary with image_url and status
    """
    try:
        # Create cache directory if it doesn't exist
        os.makedirs(CACHE_DIR, exist_ok=True)
        logger.info(f"Cache directory: {CACHE_DIR}")
        
        params = {
            "prompt": prompt,
            "negative_prompt": "(worst quality, low quality, normal quality, (variations):1.4), blur:1.5",
            "seed": -1,
            "steps": 15,
            "guidance_scale": 4,
            "batch_count": 1,  # Generate only one image
            "width": width,
            "height": height
        }
        
        async with aiohttp.ClientSession(timeout=ClientTimeout(total=300)) as session:
            async with session.post(
                DRAWTHINGS_URL,
                headers={'Content-Type': 'application/json'},
                json=params
            ) as response:
                if response.status != 200:
                    error_text = await response.text()
                    logger.error(f"DrawThings API request failed: {error_text}")
                    return {
                        "image_url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
                        "status": "error",
                        "message": f"DrawThings error: {error_text}"
                    }
                
                data = await response.json()
                
                if not data.get("images") or len(data["images"]) == 0:
                    return {
                        "image_url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
                        "status": "error",
                        "message": "No images generated by DrawThings"
                    }
                
                # Get the first image (base64 encoded)
                image_base64 = data["images"][0]
                
                # Save image
                filename = f"{uuid.uuid4()}.png"
                save_path = os.path.join(CACHE_DIR, filename)
                
                # Decode base64 and save
                image_data = base64.b64decode(image_base64)
                with open(save_path, "wb") as image_file:
                    image_file.write(image_data)
                
                logger.info(f"Image saved to: {save_path}")
                
                # Use configurable backend URL for image serving
                image_url = f"{BACKEND_URL}/static/images/{filename}"
                logger.info(f"Image URL: {image_url}")
                
                return {
                    "image_url": image_url,
                    "status": "success",
                    "message": f"Generated image locally for prompt: '{prompt}'"
                }
                
    except Exception as e:
        logger.error(f"Error generating image with DrawThings: {str(e)}")
        return {
            "image_url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
            "status": "error",
            "message": f"Error generating image with DrawThings: {str(e)}"
        }


async def generate_image_huggingface(
    prompt: str, 
    width: int = 512, 
    height: int = 512
) -> dict:
    """
    Generate an image using HuggingFace API.
    
    :param prompt: The prompt to generate the image
    :param width: Image width
    :param height: Image height
    :return: Dictionary with image_url and status
    """
    try:
        # Create cache directory if it doesn't exist
        os.makedirs(CACHE_DIR, exist_ok=True)
        logger.info(f"Cache directory: {CACHE_DIR}")
        
        headers = {"Authorization": f"Bearer {HF_API_KEY}"}
        payload = {
            "inputs": prompt,
            "parameters": {"width": width, "height": height},
        }
        
        async with aiohttp.ClientSession(timeout=ClientTimeout(total=600)) as session:
            async with session.post(HF_API_URL, headers=headers, json=payload) as response:
                if response.status != 200:
                    error_text = await response.text()
                    logger.error(f"HuggingFace API request failed: {error_text}")
                    return {
                        "image_url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
                        "status": "error",
                        "message": f"HuggingFace error: {error_text}"
                    }
                
                image_content = await response.read()
        
        # Save image
        filename = f"{uuid.uuid4()}.png"
        save_path = os.path.join(CACHE_DIR, filename)
        
        with open(save_path, "wb") as image_file:
            image_file.write(image_content)
        
        logger.info(f"Image saved to: {save_path}")
        
        # Use configurable backend URL for image serving
        image_url = f"{BACKEND_URL}/static/images/{filename}"
        logger.info(f"Image URL: {image_url}")
        
        return {
            "image_url": image_url,
            "status": "success",
            "message": f"Generated image with HuggingFace for prompt: '{prompt}'"
        }
        
    except Exception as e:
        logger.error(f"Error generating image with HuggingFace: {str(e)}")
        return {
            "image_url": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
            "status": "error",
            "message": f"Error generating image with HuggingFace: {str(e)}"
        }

async def generate_image(
    prompt: str, 
    theme: str,
    image_format: str = "default"
) -> dict:
    """
    Generate an image using either local DrawThings or HuggingFace API.
    
    :param prompt: The prompt to generate the image
    :param theme: Theme to enhance the prompt
    :param image_format: Format of the image (default, landscape, portrait, etc.)
    :return: Dictionary with image_url and status
    """
    if MOCK:
        return {
            "image_url": "/placeholder.png",
            "status": "success",
            "message": f"[Mock] Generated image for: {prompt} with theme {theme}"
        }
    
    try:
        # Format configurations
        formats = {
            "default": (256, 256),
            "square": (512, 512),
            "landscape": (768, 512),
            "landscape_large": (1024, 768),
            "portrait": (512, 768),
            "portrait_large": (768, 1024),
        }
        
        if image_format not in formats:
            image_format = "default"
        
        width, height = formats[image_format]
        
        # Enhance prompt with theme
        enhanced_prompt = f"{prompt} in {theme} style, colorful, engaging, child-friendly, mathematical illustration"
        
        if USE_LOCAL_IMAGE:
            return await generate_image_drawthings(enhanced_prompt, width, height)
        else:
            return await generate_image_huggingface(enhanced_prompt, width, height)
        
    except Exception as e:
        logger.error(f"Error generating image: {str(e)}")
        return {
            "image_url": "/placeholder.png",
            "status": "error",
            "message": f"Error generating image: {str(e)}"
        }
